import { describe, it, expect, vi, beforeAll } from "vitest";
import request from "supertest";
import sharp from "sharp";
import { removeChromakeyBackground } from "../src/services/ImageService.ts";

vi.mock("../src/services/PrismService.ts", () => ({
  default: {
    getSettings: vi.fn().mockResolvedValue({}),
    chat: vi.fn(),
  },
}));

import PrismService from "../src/services/PrismService.ts";
import creativeRoutes from "../src/routes/CreativeRoutes.ts";
import { createTestApp } from "./testApp.ts";

const app = createTestApp("/creative", creativeRoutes);

/** Red 100×100 square centered on a 200×200 background of the given color */
async function makeSubjectOnBackground(background: {
  r: number;
  g: number;
  b: number;
}): Promise<Buffer> {
  const square = await sharp({
    create: {
      width: 100,
      height: 100,
      channels: 3,
      background: { r: 200, g: 30, b: 40 },
    },
  })
    .png()
    .toBuffer();

  return sharp({
    create: { width: 200, height: 200, channels: 3, background },
  })
    .composite([{ input: square, left: 50, top: 50 }])
    .png()
    .toBuffer();
}

async function readRgbaPixel(png: Buffer, x: number, y: number) {
  const { data, info } = await sharp(png)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });
  const offset = (y * info.width + x) * info.channels;
  return {
    r: data[offset],
    g: data[offset + 1],
    b: data[offset + 2],
    alpha: data[offset + 3],
  };
}

describe("removeChromakeyBackground", () => {
  it("keys out a pure #00FF00 background and keeps the subject opaque", async () => {
    const input = await makeSubjectOnBackground({ r: 0, g: 255, b: 0 });
    const result = await removeChromakeyBackground(input);

    expect(result.keyed).toBe(true);
    expect(result.backgroundFraction).toBeGreaterThan(0.7);
    expect(result.backgroundFraction).toBeLessThan(0.85);

    const corner = await readRgbaPixel(result.buffer, 5, 5);
    expect(corner.alpha).toBe(0);

    const center = await readRgbaPixel(result.buffer, 100, 100);
    expect(center.alpha).toBe(255);
    expect(center.r).toBe(200);
  });

  it("tolerates slightly off-pure greens as generated by image models", async () => {
    const input = await makeSubjectOnBackground({ r: 30, g: 230, b: 45 });
    const result = await removeChromakeyBackground(input);

    expect(result.keyed).toBe(true);
    const corner = await readRgbaPixel(result.buffer, 5, 5);
    expect(corner.alpha).toBe(0);
  });

  it("reports keyed=false when there is no green background to remove", async () => {
    const input = await makeSubjectOnBackground({ r: 40, g: 60, b: 220 });
    const result = await removeChromakeyBackground(input);

    expect(result.keyed).toBe(false);
    expect(result.backgroundFraction).toBeLessThan(0.03);

    const corner = await readRgbaPixel(result.buffer, 5, 5);
    expect(corner.alpha).toBe(255);
  });

  it("does not key out desaturated or dark greens (subject protection)", async () => {
    const input = await makeSubjectOnBackground({ r: 60, g: 110, b: 70 });
    const result = await removeChromakeyBackground(input);

    expect(result.keyed).toBe(false);
  });
});

describe("POST /creative/generate-image with transparentBackground", () => {
  beforeAll(async () => {
    const greenImage = await makeSubjectOnBackground({ r: 0, g: 255, b: 0 });
    vi.mocked(PrismService.chat).mockResolvedValue({
      text: "a red square",
      images: [{ data: greenImage.toString("base64"), mimeType: "image/png" }],
    });
  });

  it("appends the greenscreen directive to the model prompt", async () => {
    const res = await request(app)
      .post("/creative/generate-image")
      .send({ prompt: "a red square sticker", transparentBackground: true });

    expect(res.status).toBe(200);
    const chatCall = vi.mocked(PrismService.chat).mock.calls.at(-1)?.[0] as {
      messages: { content: string }[];
    };
    expect(chatCall.messages[0].content).toContain("a red square sticker");
    expect(chatCall.messages[0].content).toContain("#00FF00");
  });

  it("returns a PNG with real alpha and flags transparencyApplied", async () => {
    const res = await request(app)
      .post("/creative/generate-image")
      .send({ prompt: "a red square sticker", transparentBackground: true });

    expect(res.status).toBe(200);
    expect(res.body.success).toBe(true);
    expect(res.body.transparencyApplied).toBe(true);
    expect(res.body.image.mimeType).toBe("image/png");

    const corner = await readRgbaPixel(
      Buffer.from(res.body.image.data, "base64"),
      5,
      5,
    );
    expect(corner.alpha).toBe(0);
  });

  it("leaves the prompt and image untouched without the flag", async () => {
    const res = await request(app)
      .post("/creative/generate-image")
      .send({ prompt: "a red square" });

    expect(res.status).toBe(200);
    expect(res.body.transparencyApplied).toBeUndefined();
    const chatCall = vi.mocked(PrismService.chat).mock.calls.at(-1)?.[0] as {
      messages: { content: string }[];
    };
    expect(chatCall.messages[0].content).toBe("a red square");

    const corner = await readRgbaPixel(
      Buffer.from(res.body.image.data, "base64"),
      5,
      5,
    );
    expect(corner.alpha).toBe(255);
  });

  it("passes aspectRatio and normalized size through to Prism", async () => {
    const res = await request(app)
      .post("/creative/generate-image")
      .send({ prompt: "a wide banner", aspectRatio: "16:9", size: "2k" });

    expect(res.status).toBe(200);
    const chatCall = vi.mocked(PrismService.chat).mock.calls.at(-1)?.[0] as {
      aspectRatio?: string;
      imageSize?: string;
    };
    expect(chatCall.aspectRatio).toBe("16:9");
    expect(chatCall.imageSize).toBe("2K");
  });

  it("omits image config fields from the Prism call when not requested", async () => {
    const res = await request(app)
      .post("/creative/generate-image")
      .send({ prompt: "a red square" });

    expect(res.status).toBe(200);
    const chatCall = vi.mocked(PrismService.chat).mock.calls.at(-1)?.[0] as Record<
      string,
      unknown
    >;
    expect("aspectRatio" in chatCall).toBe(false);
    expect("imageSize" in chatCall).toBe(false);
  });

  it("rejects invalid aspectRatio and size values", async () => {
    const badRatio = await request(app)
      .post("/creative/generate-image")
      .send({ prompt: "x", aspectRatio: "7:3" });
    expect(badRatio.status).toBe(400);
    expect(badRatio.body.error).toContain("aspectRatio");

    const badSize = await request(app)
      .post("/creative/generate-image")
      .send({ prompt: "x", size: "8K" });
    expect(badSize.status).toBe(400);
    expect(badSize.body.error).toContain("size");
  });

  it("delivers the opaque image with a note when keying finds no green", async () => {
    const blueImage = await makeSubjectOnBackground({ r: 40, g: 60, b: 220 });
    vi.mocked(PrismService.chat).mockResolvedValueOnce({
      text: "a red square",
      images: [{ data: blueImage.toString("base64"), mimeType: "image/png" }],
    });

    const res = await request(app)
      .post("/creative/generate-image")
      .send({ prompt: "a red square", transparentBackground: true });

    expect(res.status).toBe(200);
    expect(res.body.success).toBe(true);
    expect(res.body.transparencyApplied).toBe(false);
    expect(res.body.message).toContain("could not be reliably keyed out");
  });
});
